---
# tasks file for vagrant - EL Family

- name: EL Family | Downloading archive for {{ vagrant_app }} {{ vagrant_version }} temporarily to {{ vagrant_dl_loc }}
  get_url:
    url: "{{ vagrant_dl_url }}/{{ vagrant_app }}/{{ vagrant_version }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_osarch }}.zip"
    dest: "{{ vagrant_dl_loc }}"

- name: EL Family | Install unzip if it is  currently not in an installed state
  yum:
    name: unzip
    state: present
    update_cache: yes

- name: EL Family | Extract {{ vagrant_app }} archive
  unarchive:
    src: "{{ vagrant_dl_loc }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_os }}_{{ vagrant_arch }}.zip"
    dest: "{{ vagrant_bin_path }}"
    owner: "{{ vagrant_file_owner }}"
    group: "{{ vagrant_file_group }}"
    mode: "{{ vagrant_file_mode }}"
    remote_src: true

- name: EL Family | Remove {{ vagrant_app }} archive
  file:
    path: "{{ vagrant_dl_loc }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_osarch }}.zip"
    state: absent
