---
# tasks file for vagrant - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading archive for {{ vagrant_app }} {{ vagrant_version }} temporarily to {{ vagrant_dl_loc }}
  ansible.builtin.get_url:
    url: "{{ vagrant_dl_url }}/{{ vagrant_app }}/{{ vagrant_version }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_os }}_{{ vagrant_arch }}.zip"
    dest: "{{ vagrant_dl_loc }}"

- name: Debian/Ubuntu Family | Install unzip if it is currently not in an installed state
  ansible.builtin.apt:
    name: unzip
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Debian/Ubuntu Family | Extract {{ vagrant_app }} archive
  ansible.builtin.unarchive:
    src: "{{ vagrant_dl_loc }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_os }}_{{ vagrant_arch }}.zip"
    dest: "{{ vagrant_bin_path }}"
    owner: "{{ vagrant_file_owner }}"
    group: "{{ vagrant_file_group }}"
    mode: "{{ vagrant_file_mode }}"
    remote_src: true

- name: Debian/Ubuntu Family | Remove {{ vagrant_app }}
  ansible.builtin.file:
    path: "{{ vagrant_dl_loc }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_os }}_{{ vagrant_arch }}.zip"
    state: absent
