---
# tasks file for vagrant - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading archive for {{ vagrant_app }} {{ vagrant_version }} temporarily to {{ vagrant_dl_loc }}
  get_url:
    url: "{{ vagrant_dl_url }}/{{ vagrant_app }}/{{ vagrant_version }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_osarch }}.zip"
    dest: "{{ vagrant_dl_loc }}"

# - name: Install python3-apt on Debian based systems, required for package_facts.
#   apt:
#     name: python3-apt
#     state: present
#     force_apt_get: yes
#     update_cache: yes

# - name: Gather package facts to verify if unzip is installed on Debian based systems
#   package_facts:
#     manager: apt

- name: Debian/Ubuntu Family | Install unzip if it is currently not in an installed state
  apt:
    name: unzip
    state: present
    force_apt_get: yes
    update_cache: yes
    # when: packages['unzip'] is not defined

- name: Debian/Ubuntu Family | Extract {{ vagrant_app }} archive
  unarchive:
    src: "{{ vagrant_dl_loc }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_osarch }}.zip"
    dest: "{{ vagrant_bin_path }}"
    remote_src: true

# - name: Uninstalling unzip as it was originally not in installed state on Debian based systems.
#   apt:
#     name: unzip
#     state: absent
#     force_apt_get: yes
#     update_cache: yes
#   when: packages['unzip'] is not defined

- name: Debian/Ubuntu Family | Remove {{ vagrant_app }}
  file:
    path: "{{ vagrant_dl_loc }}/{{ vagrant_app }}_{{ vagrant_version }}_{{ vagrant_osarch }}.zip"
    state: absent
